"""Spec JSON Schema generation and offline validation.

Two entry points:

* :func:`spec_json_schema` — a JSON Schema for ``SurrogateWorkflowSpec``
  generated by introspecting the dataclasses (single source of truth);
  shipped as ``surge/workflow/spec.schema.json`` for editor autocomplete.
* :func:`validate_payload` — schema-check a loaded spec dict WITHOUT
  running it: unknown keys, missing required fields, wrong types, and
  unknown model keys against the registry. Returns human-actionable
  error strings (empty list = valid). Used by ``surge validate``.
"""

from __future__ import annotations

import dataclasses
import json
import typing
from pathlib import Path
from typing import Any, Mapping

from ..hpc import ResourceSpec
from .spec import HPOConfig, ModelConfig, SurrogateWorkflowSpec

# ── JSON Schema generation ─────────────────────────────────────────────


def _type_schema(tp: Any) -> dict:
    """Best-effort JSON Schema fragment for a Python type annotation."""
    origin = typing.get_origin(tp)
    args = typing.get_args(tp)

    if tp in (str, Path) or tp == typing.Union[str, Path]:
        return {"type": "string"}
    if tp is bool:
        return {"type": "boolean"}
    if tp is int:
        return {"type": "integer"}
    if tp is float:
        return {"type": "number"}
    if tp is Any:
        return {}

    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        inner = (_type_schema(non_none[0]) if len(non_none) == 1
                 else {"anyOf": [_type_schema(a) for a in non_none]})
        if type(None) in args:
            if "type" in inner and isinstance(inner["type"], str):
                inner = {"type": [inner["type"], "null"]}
            else:
                inner = {"anyOf": [inner, {"type": "null"}]}
        return inner

    if origin in (list, typing.Sequence, tuple) or tp is tuple:
        item = _type_schema(args[0]) if args else {}
        return {"type": "array", "items": item}
    if origin is dict or tp is dict:
        return {"type": "object"}

    if dataclasses.is_dataclass(tp):
        return {"$ref": f"#/$defs/{tp.__name__}"}
    return {}


def _dataclass_schema(cls: type) -> dict:
    hints = typing.get_type_hints(cls)
    props: dict[str, Any] = {}
    required: list[str] = []
    for f in dataclasses.fields(cls):
        props[f.name] = _type_schema(hints.get(f.name, Any))
        if (f.default is dataclasses.MISSING
                and f.default_factory is dataclasses.MISSING):
            required.append(f.name)
    out: dict[str, Any] = {
        "type": "object",
        "properties": props,
        "additionalProperties": False,
    }
    if required:
        out["required"] = required
    return out


def spec_json_schema() -> dict:
    """Full JSON Schema for a SURGE workflow spec YAML."""
    schema = _dataclass_schema(SurrogateWorkflowSpec)
    schema.update({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/S-Villar/SURGE/surge/workflow/spec.schema.json",
        "title": "SURGE workflow spec",
        "description": ("Declarative surrogate workflow: load -> split -> "
                        "train -> HPO -> metrics -> artifacts."),
        "$defs": {
            "ModelConfig": _dataclass_schema(ModelConfig),
            "HPOConfig": _dataclass_schema(HPOConfig),
            "ResourceSpec": _dataclass_schema(ResourceSpec),
        },
    })
    return schema


def write_schema(path: str | Path) -> Path:
    p = Path(path)
    p.write_text(json.dumps(spec_json_schema(), indent=2) + "\n")
    return p


# ── offline validation ─────────────────────────────────────────────────

_LENIENT_OK = {
    ("integer", float),          # YAML 1 vs 1.0 mixups are harmless
    ("number", int),
    ("string", Path),
}


def _check_type(value: Any, frag: dict, where: str, errors: list[str]) -> None:
    t = frag.get("type")
    if t is None or value is None and (t == "null" or "null" in (t if isinstance(t, list) else [t])):
        return
    types = t if isinstance(t, list) else [t]
    ok = False
    for tt in types:
        if tt == "string" and isinstance(value, (str, Path)):
            ok = True
        elif tt == "boolean" and isinstance(value, bool):
            ok = True
        elif tt == "integer" and isinstance(value, int) and not isinstance(value, bool):
            ok = True
        elif tt == "number" and isinstance(value, (int, float)) and not isinstance(value, bool):
            ok = True
        elif tt == "array" and isinstance(value, (list, tuple)):
            ok = True
        elif tt == "object" and isinstance(value, Mapping):
            ok = True
        elif tt == "null" and value is None:
            ok = True
    if not ok:
        errors.append(
            f"{where}: expected {' or '.join(types)}, got "
            f"{type(value).__name__} ({value!r})")


def _validate_against(payload: Mapping[str, Any], cls: type, where: str,
                      errors: list[str]) -> None:
    import difflib

    fields = {f.name: f for f in dataclasses.fields(cls)}
    hints = typing.get_type_hints(cls)
    for key, value in payload.items():
        if key not in fields:
            hint = difflib.get_close_matches(key, fields, n=1)
            suggest = f" — did you mean '{hint[0]}'?" if hint else ""
            errors.append(f"{where}: unknown key '{key}'{suggest}")
            continue
        frag = _type_schema(hints.get(key, Any))
        if "$ref" in frag:
            continue  # nested dataclasses handled explicitly below
        _check_type(value, frag, f"{where}.{key}", errors)
    for name, f in fields.items():
        if (f.default is dataclasses.MISSING
                and f.default_factory is dataclasses.MISSING
                and name not in payload):
            errors.append(f"{where}: missing required key '{name}'")


def validate_payload(payload: Any, *, check_models: bool = True) -> list[str]:
    """Validate a loaded spec dict. Returns error strings (empty = valid)."""
    errors: list[str] = []
    if not isinstance(payload, Mapping):
        return [f"spec: top level must be a mapping, got {type(payload).__name__}"]

    _validate_against(payload, SurrogateWorkflowSpec, "spec", errors)

    models = payload.get("models", [])
    if not isinstance(models, (list, tuple)):
        errors.append("spec.models: expected a list of model blocks")
        models = []
    if not models:
        errors.append("spec.models: at least one model is required to train")

    known_keys: set[str] | None = None
    if check_models:
        try:
            from surge.model.registry import MODEL_REGISTRY
            known_keys = set(MODEL_REGISTRY.list_keys()) if hasattr(
                MODEL_REGISTRY, "list_keys") else None
            if known_keys is None:
                known_keys = {k for k in getattr(MODEL_REGISTRY, "_registry", {})}
        except Exception:  # noqa: BLE001 - validation must not hard-require torch
            known_keys = None

    import difflib
    for i, m in enumerate(models):
        where = f"spec.models[{i}]"
        if not isinstance(m, Mapping):
            errors.append(f"{where}: expected a mapping, got {type(m).__name__}")
            continue
        _validate_against(m, ModelConfig, where, errors)
        key = m.get("key")
        if key and known_keys is not None and key not in known_keys:
            hint = difflib.get_close_matches(str(key), known_keys, n=1)
            suggest = f" — did you mean '{hint[0]}'?" if hint else ""
            errors.append(
                f"{where}.key: '{key}' is not in the model registry{suggest} "
                "(optional backends register only when their package is "
                "installed; see 'surge models --verbose')")
        hpo = m.get("hpo")
        if isinstance(hpo, Mapping):
            _validate_against(hpo, HPOConfig, f"{where}.hpo", errors)
        elif hpo is not None:
            errors.append(f"{where}.hpo: expected a mapping")

    res = payload.get("resources")
    if isinstance(res, Mapping):
        _validate_against(res, ResourceSpec, "spec.resources", errors)
    elif res is not None:
        errors.append("spec.resources: expected a mapping")

    for frac in ("test_fraction", "val_fraction"):
        v = payload.get(frac)
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            if not (0.0 <= float(v) < 1.0):
                errors.append(f"spec.{frac}: must be in [0, 1), got {v}")

    return errors


def validate_file(path: str | Path, *, check_models: bool = True) -> list[str]:
    """Load a YAML spec file and validate it; file errors are returned too."""
    import yaml

    p = Path(path)
    if not p.is_file():
        return [f"spec file not found: {p}"]
    try:
        payload = yaml.safe_load(p.read_text())
    except yaml.YAMLError as exc:
        return [f"not valid YAML: {exc}"]
    return validate_payload(payload, check_models=check_models)


if __name__ == "__main__":
    out = Path(__file__).parent / "spec.schema.json"
    write_schema(out)
    print(f"wrote {out}")
