#!/usr/bin/env python3
"""Verify batch generation results.

This script verifies that batches generated by surge_batch_setup.py have:
- All expected input files present
- Parameter values correctly set in input files
- Parameter values within expected ranges
- Consistent parameters across equilibria in "fixed" mode
- Properly copied equilibrium directories

Usage:
    python3 surge/verify_batch.py /path/to/batch_N
    python3 surge/verify_batch.py /path/to/batch_N --verbose
"""

import argparse
import json
import os
import re
import sys
from typing import Any, Dict, List, Optional, Tuple


def extract_parameter_value(filepath: str, varname: str) -> Optional[float]:
    """Extract a parameter value from an input file.
    
    Looks for lines with format: varname = value
    where varname appears as a standalone token on the LHS.
    
    Returns:
        The numeric value if found, None otherwise.
    """
    if not os.path.isfile(filepath):
        return None
    
    var_pat = re.compile(rf"(?:(?<=^)|(?<=[\s.=])){re.escape(varname)}(?:(?=$)|(?=[\s.=]))")
    
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line:
                    lhs, rhs = line.split("=", 1)
                    if var_pat.search(lhs):
                        # Extract numeric value from RHS
                        rhs = rhs.strip()
                        # Try to parse as float
                        try:
                            # Remove trailing comments if any
                            if "!" in rhs or "#" in rhs:
                                rhs = rhs.split("!")[0].split("#")[0].strip()
                            return float(rhs)
                        except ValueError:
                            return None
    except Exception:
        return None
    
    return None


def load_meta_json(batch_dir: str) -> Dict[str, Any]:
    """Load meta.json from a batch directory."""
    meta_path = os.path.join(batch_dir, "meta.json")
    if not os.path.isfile(meta_path):
        raise FileNotFoundError(f"meta.json not found in {batch_dir}")
    
    with open(meta_path, "r", encoding="utf-8") as f:
        return json.load(f)


def find_sparc_dirs(run_dir: str) -> List[str]:
    """Find all sparc_* directories in a run directory."""
    if not os.path.isdir(run_dir):
        return []
    
    sparc_dirs = []
    for item in os.listdir(run_dir):
        item_path = os.path.join(run_dir, item)
        if os.path.isdir(item_path) and item.startswith("sparc_"):
            sparc_dirs.append(item)
    
    return sorted(sparc_dirs)


def check_input_file_exists(run_dir: str, sparc_case: str, inputfilename: str, verbose: bool = False) -> bool:
    """Check if input file exists in a sparc case directory."""
    inp_path = os.path.join(run_dir, sparc_case, inputfilename)
    exists = os.path.isfile(inp_path)
    
    if verbose and not exists:
        print(f"  [ERROR] Input file missing: {inp_path}")
    
    return exists


def check_parameter_in_file(
    filepath: str, 
    param_name: str, 
    expected_value: Optional[float] = None,
    expected_range: Optional[Tuple[float, float]] = None,
    is_integer: bool = False,
    verbose: bool = False
) -> Tuple[bool, Optional[str]]:
    """Check if a parameter exists in a file and optionally validate its value.
    
    Returns:
        (success, error_message)
    """
    value = extract_parameter_value(filepath, param_name)
    
    if value is None:
        return False, f"Parameter '{param_name}' not found in {filepath}"
    
    # Check if value matches expected (for fixed mode)
    if expected_value is not None:
        tolerance = 1e-6
        if abs(value - expected_value) > tolerance:
            return False, (
                f"Parameter '{param_name}' value mismatch: "
                f"expected {expected_value}, found {value}"
            )
    
    # Check if value is within expected range
    if expected_range is not None:
        min_val, max_val = expected_range
        if value < min_val or value > max_val:
            return False, (
                f"Parameter '{param_name}' value {value} out of range "
                f"[{min_val}, {max_val}]"
            )
    
    # Check integer constraint
    if is_integer:
        if abs(value - round(value)) > 1e-6:
            return False, (
                f"Parameter '{param_name}' should be integer but found {value}"
            )
    
    return True, None


def verify_set_mode_batch(
    batch_dir: str,
    meta: Dict[str, Any],
    verbose: bool = False
) -> Tuple[int, int]:
    """Verify a batch in 'set' equilibria mode.
    
    In set mode, all equilibria (sparc_*) in a run should have the same
    parameter values (multiple equilibria per run, all share same params).
    
    Returns:
        (num_errors, num_warnings)
    """
    params = meta.get("params", [])
    ranges = meta.get("ranges", [])
    integer_mask = meta.get("integer_mask", [False] * len(params))
    inputfilename = meta.get("inputfilename")
    n_runs = meta.get("n_runs", 0)
    
    # Try to find inputfilename from meta or infer from source_run_dir
    source_run_dir = meta.get("source_run_dir", "")
    if not inputfilename:
        # Try to find input file in source_run_dir
        if source_run_dir and os.path.isdir(source_run_dir):
            # Check for common input files in source_run_dir or its sparc_* subdirectories
            common_inputs = ["C1input", "global_ns.py"]
            for item in os.listdir(source_run_dir):
                item_path = os.path.join(source_run_dir, item)
                if os.path.isfile(item_path) and item in common_inputs:
                    inputfilename = item
                    break
                elif os.path.isdir(item_path) and item.startswith("sparc_"):
                    # Check inside sparc directory
                    for inp_file in common_inputs:
                        inp_path = os.path.join(item_path, inp_file)
                        if os.path.isfile(inp_path):
                            inputfilename = inp_file
                            break
                    if inputfilename:
                        break
    
    # Fallback: try to infer from first run's first sparc directory
    if not inputfilename:
        first_run_dir = os.path.join(batch_dir, "run1")
        if os.path.isdir(first_run_dir):
            sparc_dirs = find_sparc_dirs(first_run_dir)
            if sparc_dirs:
                first_sparc_path = os.path.join(first_run_dir, sparc_dirs[0])
                for item in os.listdir(first_sparc_path):
                    item_path = os.path.join(first_sparc_path, item)
                    if os.path.isfile(item_path) and item in ["C1input", "global_ns.py"]:
                        inputfilename = item
                        break
    
    if not inputfilename:
        print("[ERROR] Could not determine input filename")
        return 1, 0
    
    if verbose:
        print(f"Verifying fixed mode batch:")
        print(f"  Batch directory: {batch_dir}")
        print(f"  Parameters: {params}")
        print(f"  Input filename: {inputfilename}")
        print(f"  Number of runs: {n_runs}")
        print()
    
    errors = 0
    warnings = 0
    
    # Check each run
    for run_idx in range(1, n_runs + 1):
        run_dir = os.path.join(batch_dir, f"run{run_idx}")
        
        if not os.path.isdir(run_dir):
            print(f"[ERROR] Run directory not found: {run_dir}")
            errors += 1
            continue
        
        if verbose:
            print(f"Checking run{run_idx}...")
        
        # Find all sparc_* directories
        sparc_dirs = find_sparc_dirs(run_dir)
        
        if not sparc_dirs:
            print(f"  [WARNING] No sparc_* directories found in {run_dir}")
            warnings += 1
            continue
        
        if verbose:
            print(f"  Found {len(sparc_dirs)} equilibria: {sparc_dirs}")
        
        # Check first equilibrium to get expected parameter values
        first_sparc = sparc_dirs[0]
        first_inp_path = os.path.join(run_dir, first_sparc, inputfilename)
        
        # Check input file exists
        if not check_input_file_exists(run_dir, first_sparc, inputfilename, verbose):
            errors += 1
            continue
        
        # Extract parameter values from first equilibrium
        expected_values = {}
        for param in params:
            value = extract_parameter_value(first_inp_path, param)
            if value is None:
                print(f"  [ERROR] Parameter '{param}' not found in {first_inp_path}")
                errors += 1
            else:
                expected_values[param] = value
                param_idx = params.index(param)
                param_range = ranges[param_idx] if param_idx < len(ranges) else None
                is_int = integer_mask[param_idx] if param_idx < len(integer_mask) else False
                
                # Check value is in range
                if param_range:
                    min_val, max_val = param_range
                    success, msg = check_parameter_in_file(
                        first_inp_path, param, 
                        expected_range=(min_val, max_val),
                        is_integer=is_int,
                        verbose=verbose
                    )
                    if not success:
                        print(f"  [ERROR] {msg}")
                        errors += 1
        
        # Check all other equilibria have the same values
        for sparc_case in sparc_dirs[1:]:
            inp_path = os.path.join(run_dir, sparc_case, inputfilename)
            
            # Check file exists
            if not check_input_file_exists(run_dir, sparc_case, inputfilename, verbose):
                errors += 1
                continue
            
            # Check all parameters match
            for param, expected_val in expected_values.items():
                param_idx = params.index(param)
                is_int = integer_mask[param_idx] if param_idx < len(integer_mask) else False
                
                success, msg = check_parameter_in_file(
                    inp_path, param,
                    expected_value=expected_val,
                    is_integer=is_int,
                    verbose=verbose
                )
                
                if not success:
                    print(f"  [ERROR] {sparc_case}: {msg}")
                    errors += 1
                elif verbose:
                    print(f"    {sparc_case}/{inputfilename}: {param} = {expected_val} ✓")
        
        if verbose:
            print()
    
    return errors, warnings


def verify_fixed_mode_batch(
    batch_dir: str,
    meta: Dict[str, Any],
    verbose: bool = False
) -> Tuple[int, int]:
    """Verify a batch in 'fixed' equilibria mode.
    
    In fixed mode, all runs use the same single equilibrium but with different
    parameter values per run.
    
    Returns:
        (num_errors, num_warnings)
    """
    params = meta.get("params", [])
    ranges = meta.get("ranges", [])
    integer_mask = meta.get("integer_mask", [False] * len(params))
    inputfilename = meta.get("inputfilename")
    n_runs = meta.get("n_runs", 0)
    equilibrium = meta.get("equilibrium")  # Should be set in fixed mode
    
    # Try to find inputfilename from meta or infer from source_run_dir
    source_run_dir = meta.get("source_run_dir", "")
    if not inputfilename:
        # Try to find input file in source_run_dir
        if source_run_dir and os.path.isdir(source_run_dir):
            # Check for common input files
            common_inputs = ["C1input", "global_ns.py"]
            for item in os.listdir(source_run_dir):
                item_path = os.path.join(source_run_dir, item)
                if os.path.isfile(item_path) and item in common_inputs:
                    inputfilename = item
                    break
                elif os.path.isdir(item_path) and item.startswith("sparc_"):
                    for inp_file in common_inputs:
                        inp_path = os.path.join(item_path, inp_file)
                        if os.path.isfile(inp_path):
                            inputfilename = inp_file
                            break
                    if inputfilename:
                        break
    
    errors = 0
    warnings = 0
    
    # Check each run
    for run_idx in range(1, n_runs + 1):
        run_dir = os.path.join(batch_dir, f"run{run_idx}")
        
        if not os.path.isdir(run_dir):
            print(f"[ERROR] Run directory not found: {run_dir}")
            errors += 1
            continue
        
        if verbose:
            print(f"Checking run{run_idx}...")
        
        # Find equilibrium directory (should be only one in fixed mode)
        sparc_dirs = find_sparc_dirs(run_dir)
        
        if not sparc_dirs:
            print(f"  [WARNING] No sparc_* directories found in {run_dir}")
            warnings += 1
            continue
        
        if len(sparc_dirs) != 1:
            print(f"  [WARNING] Expected 1 equilibrium in fixed mode, found {len(sparc_dirs)}: {sparc_dirs}")
            warnings += 1
        
        # Check the equilibrium matches expected (if specified)
        if equilibrium and sparc_dirs[0] != equilibrium:
            print(f"  [WARNING] Expected equilibrium '{equilibrium}', found '{sparc_dirs[0]}'")
            warnings += 1
        
        sparc_dir = sparc_dirs[0]
        inp_path = os.path.join(run_dir, sparc_dir, inputfilename)
        
        # Check input file exists
        if not check_input_file_exists(run_dir, sparc_dir, inputfilename, verbose):
            errors += 1
            continue
        
        # Verify parameters are present and valid
        for param in params:
            param_idx = params.index(param)
            is_int = integer_mask[param_idx] if param_idx < len(integer_mask) else False
            param_range = ranges[param_idx] if param_idx < len(ranges) else None
            
            success, msg = check_parameter_in_file(
                inp_path, param,
                expected_range=param_range,
                is_integer=is_int,
                verbose=verbose
            )
            
            if not success:
                print(f"  [ERROR] {msg}")
                errors += 1
            elif verbose:
                print(f"    {sparc_dir}/{inputfilename}: {param} ✓")
        
        if verbose:
            print()
    
    return errors, warnings


def verify_per_case_mode_batch(
    batch_dir: str,
    meta: Dict[str, Any],
    verbose: bool = False
) -> Tuple[int, int]:
    """Verify a batch in 'per_case' equilibria mode.
    
    In per_case mode, each equilibrium case should have different parameter values.
    """
    # This mode is more complex - would need to check that each case has different values
    # For now, just check basic file existence
    print("[WARNING] per_case mode verification not yet fully implemented")
    return 0, 1


def verify_simple_batch(
    batch_dir: str,
    meta: Dict[str, Any],
    verbose: bool = False
) -> Tuple[int, int]:
    """Verify a simple batch (no equilibria mode)."""
    print("[INFO] Simple batch mode verification not yet implemented")
    return 0, 0


def main(batch_dir: str, verbose: bool = False) -> int:
    """Main verification function."""
    batch_dir = os.path.abspath(batch_dir)
    
    if not os.path.isdir(batch_dir):
        print(f"[ERROR] Batch directory does not exist: {batch_dir}")
        return 1
    
    # Load metadata
    try:
        meta = load_meta_json(batch_dir)
    except FileNotFoundError as e:
        print(f"[ERROR] {e}")
        return 1
    
    # Determine mode
    mode = meta.get("mode", "unknown")
    equilibria_mode = meta.get("equilibria_mode", None)
    
    print(f"Verifying batch: {batch_dir}")
    print(f"Mode: {mode}, Equilibria mode: {equilibria_mode}")
    print()
    
    # Route to appropriate verification function
    if mode == "equilibria":
        if equilibria_mode == "set":
            errors, warnings = verify_set_mode_batch(batch_dir, meta, verbose)
        elif equilibria_mode == "fixed":
            errors, warnings = verify_fixed_mode_batch(batch_dir, meta, verbose)
        elif equilibria_mode == "per_case":
            errors, warnings = verify_per_case_mode_batch(batch_dir, meta, verbose)
        else:
            print(f"[ERROR] Unknown equilibria_mode: {equilibria_mode}")
            return 1
    else:
        errors, warnings = verify_simple_batch(batch_dir, meta, verbose)
    
    # Summary
    print()
    print("=" * 60)
    print("Verification Summary:")
    print(f"  Errors: {errors}")
    print(f"  Warnings: {warnings}")
    
    if errors == 0 and warnings == 0:
        print("  Status: ✓ All checks passed")
        return 0
    elif errors == 0:
        print("  Status: ⚠ Passed with warnings")
        return 0
    else:
        print("  Status: ✗ Failed")
        return 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Verify batch generation results",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        "batch_dir",
        type=str,
        help="Path to batch directory (e.g., /path/to/batch_N)"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print detailed verification output"
    )
    
    args = parser.parse_args()
    sys.exit(main(args.batch_dir, verbose=args.verbose))
